<template>
  <v-container style="max-width: 600px;">
    <h2 class="pb-2">Repo Groupie Options</h2>
    <v-divider></v-divider>

    <h5 class="mt-4">Add New Token</h5>
    <v-form @submit.prevent="handleSaveNewToken" class="mt-2">
      <v-select
        v-model="localToken.platform"
        :items="availablePlatforms"
        label="Platform"
        required
        density="compact"
      ></v-select>
      <v-text-field
        v-model="localToken.name"
        label="Friendly Name (Optional)"
        placeholder="e.g., Personal GitHub, Work GitLab"
        density="compact"
        class="mt-2"
      ></v-text-field>
      <v-text-field
        v-model="localToken.token"
        label="Access Token"
        type="password"
        placeholder="Enter your PAT/access token"
        required
        density="compact"
        class="mt-2"
        hint="Ensure your token has the necessary scopes (e.g., 'repo' for GitHub, 'read_api' for GitLab)."
        persistent-hint
      ></v-text-field>
      <v-btn color="primary" type="submit" class="mt-3">Add Token</v-btn>
    </v-form>

    <v-alert v-if="statusMessage" :type="isError ? 'error' : 'success'" density="compact" class="mt-3 mb-3">{{ statusMessage }}</v-alert>

    <v-divider class="mt-5 mb-3"></v-divider>
    <h5>Saved Tokens</h5>
    <v-list lines="two" density="compact" v-if="tokensList.length > 0">
      <v-list-item
        v-for="tokenEntry in tokensList"
        :key="tokenEntry.id"
        :title="tokenEntry.name || tokenEntry.platform"
        :subtitle="`${tokenEntry.platform} - Token: ••••••••`"
      >
        <template v-slot:prepend>
          <!-- Placeholder for platform icon, you can use mdi icons here if Vuetify is configured with them -->
          <v-icon v-if="tokenEntry.platform === 'GitHub'">mdi-github</v-icon>
          <v-icon v-else-if="tokenEntry.platform === 'GitLab'">mdi-gitlab</v-icon>
          <v-icon v-else-if="tokenEntry.platform === 'Bitbucket'">mdi-bitbucket</v-icon>
          <v-icon v-else>mdi-key-variant</v-icon>
        </template>
        <template v-slot:append>
          <v-btn icon="mdi-delete" variant="text" color="grey-lighten-1" @click="handleDeleteToken(tokenEntry.id)"></v-btn>
        </template>
      </v-list-item>
    </v-list>
    <v-card-text v-else class="text-center grey--text">
      No tokens saved yet. Add one above.
    </v-card-text>


    <v-divider class="mt-5 mb-3"></v-divider>
    <h5>Connected Accounts Overview</h5>
    <v-table class="mt-2">
      <thead>
        <tr>
          <th class="text-left">Platform</th>
          <th class="text-left">Configured Name</th>
          <th class="text-left">Status</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="account in accounts" :key="account.platform">
          <td>{{ account.platform }}</td>
          <td>{{ account.name }}</td>
          <td>
             <v-chip :color="account.tokenExists ? 'green' : 'grey'" density="compact" label>
              {{ account.status }}
            </v-chip>
          </td>
        </tr>
      </tbody>
    </v-table>
  </v-container>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue'; // Removed onMounted as it's not used
import { useStore, PlatformToken } from '../store'; // Adjusted path and added PlatformToken

const store = useStore();

const initialLocalTokenState = (): PlatformToken => ({
  id: '', // Will be generated by the store if new, or used for editing
  platform: 'GitHub', // Default platform
  token: '',
  name: '',
});

const localToken = ref<PlatformToken>(initialLocalTokenState());
const tokensList = store.tokens; // This is already a reactive computed from the store

const statusMessage = ref('');
const isError = ref(false);

const availablePlatforms: PlatformToken['platform'][] = ['GitHub', 'GitLab', 'Bitbucket'];

// Computed property for the "Connected Accounts" table
// This version shows ONLY configured platforms/tokens as per subtask requirement.
const accounts = computed(() => {
  return tokensList.value.map(token => ({
    platform: token.platform,
    name: token.name || token.platform, // Display configured name or platform name if no specific name
    status: 'Token Stored',
    tokenExists: true,
    id: token.id,
  })).sort((a,b) => availablePlatforms.indexOf(a.platform) - availablePlatforms.indexOf(b.platform));
});


const handleSaveNewToken = async () => {
  if (!localToken.value.platform) {
    statusMessage.value = 'Platform must be selected.';
    isError.value = true;
    return;
  }
  if (!localToken.value.token.trim()) {
    statusMessage.value = 'Token cannot be empty.';
    isError.value = true;
    return;
  }
  try {
    // If localToken.value.id is empty, it's a new token.
    // If it has an id, store.saveToken should handle update-or-add logic.
    // For this UI, we are always adding as new, so ensure id is not pre-filled from previous edits
    // unless an "edit" mode is explicitly implemented. For now, always new.
    const tokenToSave: PlatformToken = {
        id: Date.now().toString(), // Generate new ID for new token
        platform: localToken.value.platform,
        token: localToken.value.token,
        name: localToken.value.name?.trim() || undefined, // Ensure name is not empty string
    };

    await store.saveToken(tokenToSave);
    statusMessage.value = `${tokenToSave.name || tokenToSave.platform} token saved successfully!`;
    isError.value = false;
    localToken.value = initialLocalTokenState(); // Reset form
  } catch (e: any) {
    console.error('Error saving token:', e);
    statusMessage.value = `Error saving token: ${e.message || 'Unknown error'}`;
    isError.value = true;
  }
};

const handleDeleteToken = async (tokenId: string) => {
  try {
    const tokenToDelete = tokensList.value.find(t => t.id === tokenId);
    await store.deleteToken(tokenId);
    statusMessage.value = `${tokenToDelete?.name || tokenToDelete?.platform || 'Token'} deleted successfully.`;
    isError.value = false;
  } catch (e: any) {
    console.error('Error deleting token:', e);
    statusMessage.value = `Error deleting token: ${e.message || 'Unknown error'}`;
    isError.value = true;
  }
};

// Watch for external changes to tokens that might affect the accounts list or other UI elements.
// For example, if tokens are cleared due to an API error detected in the store.
watch(tokensList, (newTokens) => {
  // If needed, react to changes in the tokens list.
  // For instance, if a token being edited is deleted from another source.
  // Currently, the UI should reactively update due to `tokensList` being from `store.tokens`.
  // The `accounts` computed property will also auto-update.
  console.log('Tokens list changed:', newTokens);
}, { deep: true });

</script>

<style scoped>
/* Specific styles can remain if needed, but Vuetify handles most common cases. */
/* For example, if .container had very specific padding/margin not covered by v-container default */
</style>
